const projectsData = [
  {
    title: 'Simulated World',
    description: `infinite 3d scene generated by AI with user prompt and store in filecoin blockchain that can use by everyone`,
    imgSrc: '/static/images/scene.png',
    href: 'https://github.com/SimulatedWorld/SimulatedWorld',
  },
  {
    title: 'Candle',
    description: `Minimalist ML framework for Rust`,
    imgSrc: '/static/images/time-machine.jpg',
    href: 'https://github.com/SimulatedWorld/candle',
  },
]

export default projectsData
